name: Compile pip-tool

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create Output Dir
      shell: cmd
      run: md x86 x64
      
    - name: Compile x86
      uses: CCCC-L/Action-Ahk2Exe@main
      with:
        in: pip-tool.ahk
        out: x86/pip-tool.exe
        base: 32
        
    - name: Compile x64
      uses: CCCC-L/Action-Ahk2Exe@main
      with:
        in: pip-tool.ahk
        out: x64/pip-tool.exe
        base: 64
        
    - name: Upload Artifact x86
      uses: actions/upload-artifact@master
      with:
        name: pip-tool_x86
        path: x86/pip-tool.exe
        
    - name: Upload Artifact x64
      uses: actions/upload-artifact@master
      with:
        name: pip-tool_x64
        path: x64/pip-tool.exe
