name: Compile pip-tool

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile with Ahk2Exe
      uses: CCCC-L/Action-Ahk2Exe@main
      with:
        in: pip-tool.ahk
        out: pip-tool.exe
        base: 32

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: pip-tool
        path: pip-tool.exe
